interface DateTimeRange {
  startTime: string; //YYYY-MM-DD HH:mm:ss
  endTime: string;   //YYYY-MM-DD HH:mm:ss
}

// -----------------------------------
//* CONSULTAS CON PARAMETROS
// -----------------------------------

// -----------------------------------
//? 1. CITAS DE PACIENTES CON EXCLUSION DE ESPECIALIDADES Y ESTADO DIFERENTE DE CANCELADO
// -----------------------------------
//* SQL_PATIENT_APPOINTMENTS_WITH_STATUS_OTHER_THAN_CANCELED
export const sqlPatientAppointmentsWithStatusOtherThanCanceled = ({ startTime, endTime }: DateTimeRange): string => {
  return `
    SELECT DISTINCT ABPAC.PACTID AS TIPO_DOC_PACIENTE,
        ABPAC.PACIDE AS NUM_DOCUMENTO_PACIENTE,
        NVL(REPLACE(REPLACE(REPLACE(ABPAC.PACNOM, CHR(9), ''), CHR(10), ''), CHR(13), ''), '') || ' ' ||
        NVL(REPLACE(REPLACE(REPLACE(ABPAC.PACNO2, CHR(9), ''), CHR(10), ''), CHR(13), ''), '') || ' ' ||
        NVL(REPLACE(REPLACE(REPLACE(ABPAC.PACAP1, CHR(9), ''), CHR(10), ''), CHR(13), ''), '') || ' ' ||
        NVL(REPLACE(REPLACE(REPLACE(ABPAC.PACAP2, CHR(9), ''), CHR(10), ''), CHR(13), ''), '') AS NOMBRE_PACIENTE,
        TO_CHAR(ABPAC.PACNAC, '%Y-%m-%d') AS FECHA_NACIMIENTO,
        (YEAR(TODAY) - YEAR(ABPAC.PACNAC)) - 
            CASE
                WHEN (MONTH(TODAY) < MONTH(ABPAC.PACNAC)) OR
                     (MONTH(TODAY) = MONTH(ABPAC.PACNAC) AND DAY(TODAY) < DAY(ABPAC.PACNAC)) 
                THEN 1
                ELSE 0
            END AS EDAD_PACIENTE,
        A.CTEDETDES AS ESCOLARIDAD,
        ABPAC.PACDIR AS DIRECCION,
        ABPAC.PACTEL AS TELFIJO1,
        ABPAC.PACTE2 AS TELFIJO2,
        ABPAC.PACCEL AS TELMOVIL,
        NVL(REPLACE(REPLACE(REPLACE(ABPACOTR.PACOTRNOR, CHR(9), ''), CHR(10), ''), CHR(13), ''), '') || ' ' ||
        NVL(REPLACE(REPLACE(REPLACE(ABPACOTR.PACOTRAPR, CHR(9), ''), CHR(10), ''), CHR(13), ''), '') AS NOMBRE_RESPONSABLE,
        INESP.ESPNOM AS ESPECILIDAD_MEDICO,
        ABPAC.PACCOE AS EMAIL_PACIENTE,
        (CNCIT.CITFUE || '- ' || CNCIT.CITFUE ) AS RESERVA_CITA,
        CNCIT.CITFCI AS FECHA_CITA,
        CNCIT.CITHOR AS HORA_CITA,
        CNCIT.CITDUR AS DURACION_CITA,
        CNRECOBS.RECOBSOBS AS OBSERVACIONES,
    	CNCIT.CITEST AS ESTADO_CITA,
    	'CITAS ACTIVAS' AS NO_CANCELADAS
    FROM CNCIT
    JOIN ABPAC ON ABPAC.PACHIS = CNCIT.CITHIS  AND ABPAC.PACNIE IN ('CANCER','CANCER-B24') 
    JOIN ABPACOTR ON ABPAC.PACHIS = ABPACOTR.PACOTRSEC 
    JOIN INLOC ON INLOC.LOCMUN = ABPAC.PACMUN AND INLOC.LOCCOD = ABPAC.PACLOC
    LEFT OUTER JOIN CNRECOBS ON RECOBSFUE = CNCIT.CITFUE AND RECOBSDOC = CNCIT.CITDOC
    LEFT OUTER JOIN SICTEDET A ON A.CTEDETCOD = 'ESCOLA' AND A.CTEDETPAR = ABPACOTR.PACOTRESC
    LEFT OUTER JOIN SICTEDET B ON B.CTEDETCOD = 'PTESCO' AND B.CTEDETPAR = ABPACOTR.PACOTRPAR
    LEFT OUTER JOIN SIIDE ON SIIDE.IDECOD = CNCIT.CITMED
    LEFT OUTER JOIN INESP ON INESP.ESPCOD = CNCIT.CITESP 
    WHERE CNCIT.CITEST  <> 'C'
    AND CNCIT.CITESP NOT IN ('345','577','541','540','405','553','354','328','559','580','247','527',
                            '014','521','520','532','349','501','524','536','535','528','573','569',
                            '590','522','346','518','523','519','539','047','503','013')
    AND CNCIT.CITFCI BETWEEN TO_DATE('${startTime}','%Y-%m-%d') AND TO_DATE('${endTime}','%Y-%m-%d');
  `;
}

// -----------------------------------
//? 2. CITAS DE PACIENTES CON EXCLUSION DE ESPECIALIDADES Y ESTADO CANCELADO
// -----------------------------------
//* SQL_PATIENT_APPOINTMENTS_WITH_CANCELED_STATUS
export const sqlPatientAppointmentsWithCanceledStatus  = ({ startTime, endTime }: DateTimeRange): string => {
  return `
    SELECT DISTINCT ABPAC.PACTID AS TIPO_DOC_PACIENTE,
        ABPAC.PACIDE AS NUM_DOCUMENTO_PACIENTE,
        NVL(REPLACE(REPLACE(REPLACE(ABPAC.PACNOM, CHR(9), ''), CHR(10), ''), CHR(13), ''), '') || ' ' ||
        NVL(REPLACE(REPLACE(REPLACE(ABPAC.PACNO2, CHR(9), ''), CHR(10), ''), CHR(13), ''), '') || ' ' ||
        NVL(REPLACE(REPLACE(REPLACE(ABPAC.PACAP1, CHR(9), ''), CHR(10), ''), CHR(13), ''), '') || ' ' ||
        NVL(REPLACE(REPLACE(REPLACE(ABPAC.PACAP2, CHR(9), ''), CHR(10), ''), CHR(13), ''), '') AS NOMBRE_PACIENTE,
        TO_CHAR(ABPAC.PACNAC, '%Y-%m-%d') AS FECHA_NACIMIENTO,
        (YEAR(TODAY) - YEAR(ABPAC.PACNAC)) - 
            CASE
                WHEN (MONTH(TODAY) < MONTH(ABPAC.PACNAC)) OR
                     (MONTH(TODAY) = MONTH(ABPAC.PACNAC) AND DAY(TODAY) < DAY(ABPAC.PACNAC)) 
                THEN 1
                ELSE 0
            END AS EDAD_PACIENTE,
        A.CTEDETDES AS ESCOLARIDAD,
        ABPAC.PACDIR AS DIRECCION,
        ABPAC.PACTEL AS TELFIJO1,
        ABPAC.PACTE2 AS TELFIJO2,
        ABPAC.PACCEL AS TELMOVIL,
        NVL(REPLACE(REPLACE(REPLACE(ABPACOTR.PACOTRNOR, CHR(9), ''), CHR(10), ''), CHR(13), ''), '') || ' ' ||
        NVL(REPLACE(REPLACE(REPLACE(ABPACOTR.PACOTRAPR, CHR(9), ''), CHR(10), ''), CHR(13), ''), '') AS NOMBRE_RESPONSABLE,
        INESP.ESPNOM AS ESPECILIDAD_MEDICO,
        ABPAC.PACCOE AS EMAIL_PACIENTE,
        (CNCIT.CITFUE || '- ' || CNCIT.CITFUE ) AS RESERVA_CITA,
        CNCIT.CITFCI AS FECHA_CITA,
        CNCIT.CITHOR AS HORA_CITA,
        CNCIT.CITDUR AS DURACION_CITA,
        CNRECOBS.RECOBSOBS AS OBSERVACIONES,
    	CNCIT.CITEST AS ESTADO_CITA,
    	'CITAS CANCELADAS' AS CANCELADAS
    FROM CNCIT
    JOIN ABPAC ON ABPAC.PACHIS = CNCIT.CITHIS  AND ABPAC.PACNIE IN ('CANCER','CANCER-B24') 
    JOIN ABPACOTR ON ABPAC.PACHIS = ABPACOTR.PACOTRSEC 
    JOIN INLOC ON INLOC.LOCMUN = ABPAC.PACMUN AND INLOC.LOCCOD = ABPAC.PACLOC
    LEFT OUTER JOIN CNRECOBS ON RECOBSFUE = CNCIT.CITFUE AND RECOBSDOC = CNCIT.CITDOC
    LEFT OUTER JOIN SICTEDET A ON A.CTEDETCOD = 'ESCOLA' AND A.CTEDETPAR = ABPACOTR.PACOTRESC
    LEFT OUTER JOIN SICTEDET B ON B.CTEDETCOD = 'PTESCO' AND B.CTEDETPAR = ABPACOTR.PACOTRPAR
    LEFT OUTER JOIN SIIDE ON SIIDE.IDECOD = CNCIT.CITMED
    LEFT OUTER JOIN INESP ON INESP.ESPCOD = CNCIT.CITESP 
    WHERE CNCIT.CITEST  = 'C'
    AND CNCIT.CITESP NOT IN ('345','577','541','540','405','553','354','328','559','580','247','527',
                            '014','521','520','532','349','501','524','536','535','528','573','569',
                            '590','522','346','518','523','519','539','047','503','013')
    AND CNCIT.CITFCI BETWEEN TO_DATE('${startTime}','%Y-%m-%d') AND TO_DATE('${endTime}','%Y-%m-%d');
  `;
};

