interface DateTimeRange {
  startTime: string; //YYYY-MM-DD HH:mm:ss
  endTime: string;   //YYYY-MM-DD HH:mm:ss
}

// -----------------------------------
//* CONSULTAS CON PARAMETROS
// -----------------------------------

// -----------------------------------
//? 1. CITAS DE PACIENTES CON EXCLUSION DE ESPECIALIDADES Y ESTADO DIFERENTE DE CANCELADO
// -----------------------------------
//* SQL_PATIENT_APPOINTMENTS_WITH_STATUS_OTHER_THAN_CANCELED
export const sqlPatientAppointmentsWithStatusOtherThanCanceled = ({ startTime, endTime }: DateTimeRange): string => {
  return `
    SELECT DISTINCT ABPAC.PACTID AS TIPO_DOC_PACIENTE,
        ABPAC.PACIDE AS NUM_DOCUMENTO_PACIENTE,
        NVL(REPLACE(REPLACE(REPLACE(ABPAC.PACNOM, CHR(9), ''), CHR(10), ''), CHR(13), ''), '') || ' ' ||
        NVL(REPLACE(REPLACE(REPLACE(ABPAC.PACNO2, CHR(9), ''), CHR(10), ''), CHR(13), ''), '') || ' ' ||
        NVL(REPLACE(REPLACE(REPLACE(ABPAC.PACAP1, CHR(9), ''), CHR(10), ''), CHR(13), ''), '') || ' ' ||
        NVL(REPLACE(REPLACE(REPLACE(ABPAC.PACAP2, CHR(9), ''), CHR(10), ''), CHR(13), ''), '') AS NOMBRE_PACIENTE,
        TO_CHAR(ABPAC.PACNAC, '%Y-%m-%d') AS FECHA_NACIMIENTO,
        (YEAR(TODAY) - YEAR(ABPAC.PACNAC)) - 
            CASE
                WHEN (MONTH(TODAY) < MONTH(ABPAC.PACNAC)) OR
                     (MONTH(TODAY) = MONTH(ABPAC.PACNAC) AND DAY(TODAY) < DAY(ABPAC.PACNAC)) 
                THEN 1
                ELSE 0
            END AS EDAD_PACIENTE,
        A.CTEDETDES AS ESCOLARIDAD,
        ABPAC.PACDIR AS DIRECCION,
        ABPAC.PACTEL AS TELFIJO1,
        ABPAC.PACTE2 AS TELFIJO2,
        ABPAC.PACCEL AS TELMOVIL,
        NVL(REPLACE(REPLACE(REPLACE(ABPACOTR.PACOTRNOR, CHR(9), ''), CHR(10), ''), CHR(13), ''), '') || ' ' ||
        NVL(REPLACE(REPLACE(REPLACE(ABPACOTR.PACOTRAPR, CHR(9), ''), CHR(10), ''), CHR(13), ''), '') AS NOMBRE_RESPONSABLE,
        INESP.ESPNOM AS ESPECILIDAD_MEDICO,
        ABPAC.PACCOE AS EMAIL_PACIENTE,
        (CNCIT.CITFUE || '- ' || CNCIT.CITFUE ) AS RESERVA_CITA,
        CNCIT.CITFCI AS FECHA_CITA,
        CNCIT.CITHOR AS HORA_CITA,
        CNCIT.CITDUR AS DURACION_CITA,
        CNRECOBS.RECOBSOBS AS OBSERVACIONES,
    	CNCIT.CITEST AS ESTADO_CITA,
    	'CITAS ACTIVAS' AS NO_CANCELADAS
    FROM CNCIT
    JOIN ABPAC ON ABPAC.PACHIS = CNCIT.CITHIS  AND ABPAC.PACNIE IN ('CANCER','CANCER-B24') 
    JOIN ABPACOTR ON ABPAC.PACHIS = ABPACOTR.PACOTRSEC 
    JOIN INLOC ON INLOC.LOCMUN = ABPAC.PACMUN AND INLOC.LOCCOD = ABPAC.PACLOC
    LEFT OUTER JOIN CNRECOBS ON RECOBSFUE = CNCIT.CITFUE AND RECOBSDOC = CNCIT.CITDOC
    LEFT OUTER JOIN SICTEDET A ON A.CTEDETCOD = 'ESCOLA' AND A.CTEDETPAR = ABPACOTR.PACOTRESC
    LEFT OUTER JOIN SICTEDET B ON B.CTEDETCOD = 'PTESCO' AND B.CTEDETPAR = ABPACOTR.PACOTRPAR
    LEFT OUTER JOIN SIIDE ON SIIDE.IDECOD = CNCIT.CITMED
    LEFT OUTER JOIN INESP ON INESP.ESPCOD = CNCIT.CITESP 
    WHERE CNCIT.CITEST  <> 'C'
    AND CNCIT.CITESP NOT IN ('345','577','541','540','405','553','354','328','559','580','247','527',
                            '014','521','520','532','349','501','524','536','535','528','573','569',
                            '590','522','346','518','523','519','539','047','503','013')
    AND CNCIT.CITFCI BETWEEN TO_DATE('${startTime}','%Y-%m-%d') AND TO_DATE('${endTime}','%Y-%m-%d');
  `;
}

// -----------------------------------
//? 2. CITAS DE PACIENTES CON EXCLUSION DE ESPECIALIDADES Y ESTADO CANCELADO
// -----------------------------------
//* SQL_PATIENT_APPOINTMENTS_WITH_CANCELED_STATUS
export const sqlPatientAppointmentsWithCanceledStatus  = ({ startTime, endTime }: DateTimeRange): string => {
  return `
    SELECT DISTINCT ABPAC.PACTID AS TIPO_DOC_PACIENTE,
        ABPAC.PACIDE AS NUM_DOCUMENTO_PACIENTE,
        NVL(REPLACE(REPLACE(REPLACE(ABPAC.PACNOM, CHR(9), ''), CHR(10), ''), CHR(13), ''), '') || ' ' ||
        NVL(REPLACE(REPLACE(REPLACE(ABPAC.PACNO2, CHR(9), ''), CHR(10), ''), CHR(13), ''), '') || ' ' ||
        NVL(REPLACE(REPLACE(REPLACE(ABPAC.PACAP1, CHR(9), ''), CHR(10), ''), CHR(13), ''), '') || ' ' ||
        NVL(REPLACE(REPLACE(REPLACE(ABPAC.PACAP2, CHR(9), ''), CHR(10), ''), CHR(13), ''), '') AS NOMBRE_PACIENTE,
        TO_CHAR(ABPAC.PACNAC, '%Y-%m-%d') AS FECHA_NACIMIENTO,
        (YEAR(TODAY) - YEAR(ABPAC.PACNAC)) - 
            CASE
                WHEN (MONTH(TODAY) < MONTH(ABPAC.PACNAC)) OR
                     (MONTH(TODAY) = MONTH(ABPAC.PACNAC) AND DAY(TODAY) < DAY(ABPAC.PACNAC)) 
                THEN 1
                ELSE 0
            END AS EDAD_PACIENTE,
        A.CTEDETDES AS ESCOLARIDAD,
        ABPAC.PACDIR AS DIRECCION,
        ABPAC.PACTEL AS TELFIJO1,
        ABPAC.PACTE2 AS TELFIJO2,
        ABPAC.PACCEL AS TELMOVIL,
        NVL(REPLACE(REPLACE(REPLACE(ABPACOTR.PACOTRNOR, CHR(9), ''), CHR(10), ''), CHR(13), ''), '') || ' ' ||
        NVL(REPLACE(REPLACE(REPLACE(ABPACOTR.PACOTRAPR, CHR(9), ''), CHR(10), ''), CHR(13), ''), '') AS NOMBRE_RESPONSABLE,
        INESP.ESPNOM AS ESPECILIDAD_MEDICO,
        ABPAC.PACCOE AS EMAIL_PACIENTE,
        (CNCIT.CITFUE || '- ' || CNCIT.CITFUE ) AS RESERVA_CITA,
        CNCIT.CITFCI AS FECHA_CITA,
        CNCIT.CITHOR AS HORA_CITA,
        CNCIT.CITDUR AS DURACION_CITA,
        CNRECOBS.RECOBSOBS AS OBSERVACIONES,
    	CNCIT.CITEST AS ESTADO_CITA,
    	'CITAS CANCELADAS' AS CANCELADAS
    FROM CNCIT
    JOIN ABPAC ON ABPAC.PACHIS = CNCIT.CITHIS  AND ABPAC.PACNIE IN ('CANCER','CANCER-B24') 
    JOIN ABPACOTR ON ABPAC.PACHIS = ABPACOTR.PACOTRSEC 
    JOIN INLOC ON INLOC.LOCMUN = ABPAC.PACMUN AND INLOC.LOCCOD = ABPAC.PACLOC
    LEFT OUTER JOIN CNRECOBS ON RECOBSFUE = CNCIT.CITFUE AND RECOBSDOC = CNCIT.CITDOC
    LEFT OUTER JOIN SICTEDET A ON A.CTEDETCOD = 'ESCOLA' AND A.CTEDETPAR = ABPACOTR.PACOTRESC
    LEFT OUTER JOIN SICTEDET B ON B.CTEDETCOD = 'PTESCO' AND B.CTEDETPAR = ABPACOTR.PACOTRPAR
    LEFT OUTER JOIN SIIDE ON SIIDE.IDECOD = CNCIT.CITMED
    LEFT OUTER JOIN INESP ON INESP.ESPCOD = CNCIT.CITESP 
    WHERE CNCIT.CITEST  = 'C'
    AND CNCIT.CITESP NOT IN ('345','577','541','540','405','553','354','328','559','580','247','527',
                            '014','521','520','532','349','501','524','536','535','528','573','569',
                            '590','522','346','518','523','519','539','047','503','013')
    AND CNCIT.CITFCI BETWEEN TO_DATE('${startTime}','%Y-%m-%d') AND TO_DATE('${endTime}','%Y-%m-%d');
  `;
};

interface ActivePatientParams {
  typeOfIdentification: string;
  identificationNumber: string;
}

// -----------------------------------
//? 1. Pacientes activos
//? Basado en su tipo y número de identificación
// -----------------------------------
export const sqlGetActivePatientById = ({ typeOfIdentification, identificationNumber }: ActivePatientParams): string => {
  return `
    SELECT FIRST 1 *
    FROM (
    	SELECT ABPAC.PACHIS AS HISTORIA,
    	HIEPIACT.EPIACTEPI AS EPISODIO,
    	NVL(REPLACE(REPLACE(REPLACE(ABPAC.PACNOM, CHR(9), ''), CHR(10), ''), CHR(13), ''), '') || ' ' ||
    	NVL(REPLACE(REPLACE(REPLACE(ABPAC.PACNO2, CHR(9), ''), CHR(10), ''), CHR(13), ''), '') AS NOMBRES,
    	NVL(REPLACE(REPLACE(REPLACE(ABPAC.PACAP1, CHR(9), ''), CHR(10), ''), CHR(13), ''), '') || ' ' ||
    	NVL(REPLACE(REPLACE(REPLACE(ABPAC.PACAP2, CHR(9), ''), CHR(10), ''), CHR(13), ''), '') AS APELLIDOS,
    	NVL(REPLACE(REPLACE(REPLACE(ABPAC.PACNOM, CHR(9), ''), CHR(10), ''), CHR(13), ''), '') || ' ' ||
    	NVL(REPLACE(REPLACE(REPLACE(ABPAC.PACNO2, CHR(9), ''), CHR(10), ''), CHR(13), ''), '') || ' ' ||
    	NVL(REPLACE(REPLACE(REPLACE(ABPAC.PACAP1, CHR(9), ''), CHR(10), ''), CHR(13), ''), '') || ' ' ||
    	NVL(REPLACE(REPLACE(REPLACE(ABPAC.PACAP2, CHR(9), ''), CHR(10), ''), CHR(13), ''), '') AS NOMBRE_COMPLETO,
    	ABPAC.PACTID AS TIPO_IDENTIFICACION,
    	ABPAC.PACIDE AS IDENTIFICACION,
    	ABPAC.PACNAC AS FECHA_NACIMIENTO,
    	(YEAR(TODAY) - YEAR(ABPAC.PACNAC)) - 
    	  CASE
    		  WHEN (MONTH(TODAY) < MONTH(ABPAC.PACNAC)) OR
    			   (MONTH(TODAY) = MONTH(ABPAC.PACNAC) AND DAY(TODAY) < DAY(ABPAC.PACNAC)) 
    		  THEN 1
    		  ELSE 0
    	  END AS EDAD,
    	ABPAC.PACSEX AS SEXO,
    	ABPAC.PACEST AS ESTADO_CIVIL,
    	ABPAC.PACTEL AS TELEFONO,
    	ABPAC.PACCEL AS CELULAR,
    	ABPAC.PACDIR AS DIRECCION,
    	HIEPIACT.EPIACTRES AS RESPONSABLE_EPS,
    	(HHEPIDIA.EPIDIADIA || ' - ' || INDIA.DIANOM) AS DIAGNOSTICo_PPAL, 
    	HIEPIACT.EPIACTUBI AS COD_UBICACION,
    	INUBI.UBINOM AS UBICACION,
    	INSER.SERCOD AS COD_SERVICIO,
    	INSER.SERNOM AS SERVICIO,
    	HIEPIACT.EPIACTHAB AS CAMA,
    	'PACIENTE ACTIVO' AS ESTADO_PACIENTE,
    	1 AS PRIORIDAD,
    	HITEP.TEPNOM AS TIPO_ATENCION
    	FROM ABPAC,HIEPIACT
    	JOIN HHEPIDIA ON HIEPIACT.EPIACTEPI = HHEPIDIA.EPIDIAEPI 
    				 AND HHEPIDIA.EPIDIAPPL = 'S' 
    				 AND HHEPIDIA.EPIDIAEST IN ('C', 'E')
    	JOIN INHAB ON INHAB.HABCOD = HIEPIACT.EPIACTHAB AND INHAB.HABACT='S'
    	JOIN INDIA ON INDIA.DIACOD = HHEPIDIA.EPIDIADIA
    	JOIN INUBI ON INUBI.UBICOD = INHAB.HABUBI AND INUBI.UBICOD  = HIEPIACT.EPIACTUBI 
    	JOIN INSER ON INSER.SERCOD = INUBI.UBISER
    	JOIN HITEP ON HITEP.TEPCOD = HIEPIACT.EPIACTTEP
    	WHERE HIEPIACT.EPIACTHIS = ABPAC.PACHIS
    	UNION ALL
    	SELECT ABPAC.PACHIS AS HISTORIA,
    	HIEPIINA.EPIINAEPI AS EPISODIO,
    	NVL(REPLACE(REPLACE(REPLACE(ABPAC.PACNOM, CHR(9), ''), CHR(10), ''), CHR(13), ''), '') || ' ' ||
    	NVL(REPLACE(REPLACE(REPLACE(ABPAC.PACNO2, CHR(9), ''), CHR(10), ''), CHR(13), ''), '') AS NOMBRES,
    	NVL(REPLACE(REPLACE(REPLACE(ABPAC.PACAP1, CHR(9), ''), CHR(10), ''), CHR(13), ''), '') || ' ' ||
    	NVL(REPLACE(REPLACE(REPLACE(ABPAC.PACAP2, CHR(9), ''), CHR(10), ''), CHR(13), ''), '') AS APELLIDOS,
    	NVL(REPLACE(REPLACE(REPLACE(ABPAC.PACNOM, CHR(9), ''), CHR(10), ''), CHR(13), ''), '') || ' ' ||
    	NVL(REPLACE(REPLACE(REPLACE(ABPAC.PACNO2, CHR(9), ''), CHR(10), ''), CHR(13), ''), '') || ' ' ||
    	NVL(REPLACE(REPLACE(REPLACE(ABPAC.PACAP1, CHR(9), ''), CHR(10), ''), CHR(13), ''), '') || ' ' ||
    	NVL(REPLACE(REPLACE(REPLACE(ABPAC.PACAP2, CHR(9), ''), CHR(10), ''), CHR(13), ''), '') AS NOMBRE_COMPLETO,
    	ABPAC.PACTID AS TIPO_IDENTIFICACION,
    	ABPAC.PACIDE AS IDENTIFICACION,
    	ABPAC.PACNAC AS FECHA_NACIMIENTO,
    	(YEAR(TODAY) - YEAR(ABPAC.PACNAC)) - 
    	  CASE
    		  WHEN (MONTH(TODAY) < MONTH(ABPAC.PACNAC)) OR
    			   (MONTH(TODAY) = MONTH(ABPAC.PACNAC) AND DAY(TODAY) < DAY(ABPAC.PACNAC)) 
    		  THEN 1
    		  ELSE 0
    	  END AS EDAD,
    	ABPAC.PACSEX AS SEXO,
    	ABPAC.PACEST AS ESTADO_CIVIL,
    	ABPAC.PACTEL AS TELEFONO,
    	ABPAC.PACCEL AS CELULAR,
    	ABPAC.PACDIR AS DIRECCION,
    	HIEPIINA.EPIINARES AS RESPONSABLE_EPS,
    	(HHEPIDIA.EPIDIADIA || ' - ' || INDIA.DIANOM) AS DIAGNOSTICo_PPAL, 
    	HIEPIINA.EPIINAUBI AS COD_UBICACION,
    	INUBI.UBINOM AS UBICACION,
    	INSER.SERCOD AS COD_SERVICIO,
    	INSER.SERNOM AS SERVICIO,
    	HIEPIINA.EPIINAHAB AS CAMA,
    	'PACIENTE AMBULATORIO' AS ESTADO_PACIENTE,
    	2 AS PRIORIDAD,
    	HITEP.TEPNOM AS TIPO_ATENCION
    	FROM ABPAC, HIEPIINA
    	JOIN HHEPIDIA ON HIEPIINA.EPIINAEPI = HHEPIDIA.EPIDIAEPI 
    				 AND HHEPIDIA.EPIDIAPPL = 'S' 
    				 AND HHEPIDIA.EPIDIAEST IN ('C', 'E')
    	JOIN INHAB ON INHAB.HABCOD = HIEPIINA.EPIINAHAB AND INHAB.HABACT='S'
    	JOIN INDIA ON INDIA.DIACOD = HHEPIDIA.EPIDIADIA
    	JOIN INUBI ON INUBI.UBICOD = INHAB.HABUBI AND INUBI.UBICOD  = HIEPIINA.EPIINAUBI 
    	JOIN INSER ON INSER.SERCOD = INUBI.UBISER
    	JOIN HITEP ON HITEP.TEPCOD = HIEPIINA.EPIINATEP
    	WHERE HIEPIINA.EPIINAHIS = ABPAC.PACHIS
    ) AS PACIENTE
    WHERE PACIENTE.TIPO_IDENTIFICACION = '${typeOfIdentification}'
    AND PACIENTE.IDENTIFICACION = '${identificationNumber}'
    ORDER BY PACIENTE.PRIORIDAD;
  `;
};